replicaCount: 3

name: "details"

image:
  repository: stehedor/09_details
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


service:
  type: ClusterIP
  port: 9080

