# Default values for productpage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: "productpage"

image:
  repository: stehedor/09_productpage
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "seg"


service:
  type: LoadBalancer
  port: 9080
