# Default values for reviews.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: "reviews"

deployments:
  - name: reviews-v1
    image:
      repository: stehedor/09_reviews
      tag: v1
      pullPolicy: IfNotPresent
  - name: reviews-v2
    image:
      repository: stehedor/09_reviews
      tag: v2
      pullPolicy: IfNotPresent
  - name: reviews-v3
    image:
      repository: stehedor/09_reviews
      tag: v3
      pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 9080


