# Default values for ratings.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: stehedor/09_ratings
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

name: "ratings"

service:
  type: ClusterIP
  port: 9080
