apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "details.fullname" . }}
  labels:
    app: {{ include "details.fullname" . }}
    service: {{ include "details.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "details.fullname" . }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "details.fullname" . }}
        version: v1
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port}}
        securityContext:
          runAsUser: 1000