apiVersion: v1
kind: Service
metadata:
  name:  {{ include "details.fullname" . }}
  labels:
    app: {{ include "details.fullname" . }}
    service: {{ include "details.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: {{ include "details.fullname" . }}