apiVersion: v1
kind: Service
metadata:
  name:  {{ include "details.fullname" . }}
  labels:
    {{- include "ratings.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    {{- include "ratings.selectorLabels" . | nindent 4 }}